variables:
  GIT_SUBMODULE_STRATEGY: recursive

hello world:
  script:
    - echo "Hello World"
    - find . -path ./.git -prune -o -print

build:
  script:
    - mkdir build
    - cd build
    - cmake ../source
    - cmake --build .
